default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 30


development:
  <<: *default
  database: contactbook_development
  username: pguser
  password: pguser

test:
  <<: *default
  database: contactbook_development

production:
  <<: *default
  database: contactbook_production
  username: contactbook
  password: contactbook